debug: false

spring:
  application:
    name: filocitas-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://http://192.168.1.139:32080/realms/xavelo
          jwk-set-uri: https://http://192.168.1.139:32080/realms/xavelo/protocol/openid-connect/certs
  datasource:
    url: ${DB_URL:jdbc:h2:mem:appdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:${DATABASE_POOL_SIZE:5}}
      minimum-idle: ${DB_MIN_IDLE:1}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000} # 5 minutes
      max-lifetime: ${DB_MAX_LIFETIME:1800000} # 30 minutes
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      pool-name: FilocitasHikariPool
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: public
    baselineVersion: 0
    baselineOnMigrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # create|create-drop|update|validate|none
    show-sql: true
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.xavelo.filocitas.adapter: DEBUG
